from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='quixlab_index'),

    path('app-calender.html', views.app_calender, name='app_calender'),
    path('app-profile.html', views.app_profile, name='app_profile'),
    path('blank.html', views.blank, name='blank'),
    path('chart-chartist.html', views.chart_chartist, name='chart_chartist'),
    path('chart-chartjs.html', views.chart_chartjs, name='chart_chartjs'),
    path('chart-flot.html', views.chart_flot, name='chart_flot'),
    path('chart-morris.html', views.chart_morris, name='chart_morris'),
    path('chart-peity.html', views.chart_peity, name='chart_peity'),
    path('chart-sparkline.html', views.chart_sparkline, name='chart_sparkline'),
    path('email-compose.html', views.email_compose, name='email_compose'),
    path('email-inbox.html', views.email_inbox, name='email_inbox'),
    path('email-read.html', views.email_read, name='email_read'),
    path('form-basic.html', views.form_basic, name='form_basic'),
    path('form-editor.html', views.form_editor, name='form_editor'),
    path('form-picker.html', views.form_picker, name='form_picker'),
    path('form-step.html', views.form_step, name='form_step'),
    path('form-validation.html', views.form_validation, name='form_validation'),
    path('layout-blank.html', views.layout_blank, name='layout_blank'),
    path('layout-boxed.html', views.layout_boxed, name='layout_boxed'),
    path('layout-compact-nav.html', views.layout_compact_nav, name='layout_compact_nav'),
    path('layout-dark.html', views.layout_dark, name='layout_dark'),
    path('layout-fixed-header.html', views.layout_fixed_header, name='layout_fixed_header'),
    path('layout-fixed-sidebar.html', views.layout_fixed_sidebar, name='layout_fixed_sidebar'),
    path('layout-horizontal.html', views.layout_horizontal, name='layout_horizontal'),
    path('layout-light.html', views.layout_light, name='layout_light'),
    path('layout-one-column.html', views.layout_one_column, name='layout_one_column'),
    path('layout-two-column.html', views.layout_two_column, name='layout_two_column'),
    path('layout-vertical.html', views.layout_vertical, name='layout_vertical'),
    path('layout-wide.html', views.layout_wide, name='layout_wide'),
    path('page-error-400.html', views.page_error_400, name='page_error_400'),
    path('page-error-403.html', views.page_error_403, name='page_error_403'),
    path('page-error-404.html', views.page_error_404, name='page_error_404'),
    path('page-error-500.html', views.page_error_500, name='page_error_500'),
    path('page-error-503.html', views.page_error_503, name='page_error_503'),
    path('page-lock.html', views.page_lock, name='page_lock'),
    path('page-login.html', views.page_login, name='page_login'),
    path('page-register.html', views.page_register, name='page_register'),
    path('table-basic.html', views.table_basic, name='table_basic'),
    path('table-datatable.html', views.table_datatable, name='table_datatable'),
    path('uc-nestedable.html', views.uc_nestedable, name='uc_nestedable'),
    path('uc-noui-slider.html', views.uc_noui_slider, name='uc_noui_slider'),
    path('uc-sweetalert.html', views.uc_sweetalert, name='uc_sweetalert'),
    path('uc-toastr.html', views.uc_toastr, name='uc_toastr'),
    path('ui-accordion.html', views.ui_accordion, name='ui_accordion'),
    path('ui-alert.html', views.ui_alert, name='ui_alert'),
    path('ui-badge.html', views.ui_badge, name='ui_badge'),
    path('ui-button-group.html', views.ui_button_group, name='ui_button_group'),
    path('ui-button.html', views.ui_button, name='ui_button'),
    path('ui-cards.html', views.ui_cards, name='ui_cards'),
    path('ui-carousel.html', views.ui_carousel, name='ui_carousel'),
    path('ui-dropdown.html', views.ui_dropdown, name='ui_dropdown'),
    path('ui-list-group.html', views.ui_list_group, name='ui_list_group'),
    path('ui-media-object.html', views.ui_media_object, name='ui_media_object'),
    path('ui-modal.html', views.ui_modal, name='ui_modal'),
    path('ui-pagination.html', views.ui_pagination, name='ui_pagination'),
    path('ui-popover.html', views.ui_popover, name='ui_popover'),
    path('ui-progressbar.html', views.ui_progressbar, name='ui_progressbar'),
    path('ui-tab.html', views.ui_tab, name='ui_tab'),
    path('ui-typography.html', views.ui_typography, name='ui_typography'),
    path('widgets.html', views.widgets, name='widgets'),

]
